# 项目设置
site_name: Lan's Blog
site_url: https://lan-kehan.github.io/
repo_url: https://github.com/lan-kehan/lan-kehan.github.io
repo_name: lan-kehan/lan-kehan.github.io
edit_uri: blob/main/docs/
site_description: site description
site_author: lan-kehan
copyright: lan-kehan

nav:
  # 工具使用/技术记录
  - Cheat: 
    - section1/git.md
    - section1/linux.md
    - section1/docker.md
  # 课程笔记/资料整理
  - Notes:
    - section2/24-fall-C-programming.md
    - section2/LeetCode.md
    - section2/RL4LLM.md
  # 论文阅读
  - Reviews:
    - section3/论文精读-SAMWISE.md
    - section3/论文精读-GLUS.md
    - section3/论文精读-SegAgent.md
    - section3/论文精读-SAM-R1.md
    - section3/论文精读-Seg-R1.md
    - section3/论文精读-SegZero.md
  # 随笔/影评，乐评
  - Others:
    - section4/index.md

theme:
  name: material
  # logo: assets/zjusct.svg
  # favicon: assets/zjusct-hpc101.svg
  palette:
    # 浅色主题
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: 切换至深色主题
    # 深色主题
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 切换至科技风主题
    # 科技风主题
    - scheme: tmp
      primary: cyan
      accent: pink
      toggle:
        icon: material/ghost
        name: 切换至浅色主题
  features:
    # 代码块操作
    - content.code.copy
    - content.code.select
    - content.code.annotate
    # 底部导航
    - navigation.footer
    # 顶部导航
    - navigation.tabs
    # 侧边栏按 section 展开
    - navigation.sections
    - navigation.expand
    # 章节首页 index.md
    # - navigation.indexes
    # 锚点
    - navigation.tracking
    # 路径
    - navigation.path
    # 回到顶部
    - navigation.top
    - toc.follow
    # 页面编辑
    - content.action.edit
    # 搜索
    - search.suggest
    - search.highlight
    - search.share

markdown_extensions:
  # Admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      # Mermaid
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # Code Block
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # Tab Card
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # Grid, Image
  - attr_list
  - md_in_html
  # Icon
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # List
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # TOC
  - toc:
      permalink: true
      # 中文锚点
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  # MathJax
  - pymdownx.arithmatex:
      generic: true
  # Keys
  - pymdownx.keys
  # Highlight
  - pymdownx.critic
  # 时间轴、甘特图
  - neoteroi.timeline
  - neoteroi.projects
  - neoteroi.cards

extra_javascript:
  # 网站标题点击功能
  - javascripts/header-navigation.js
  # MathJax
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/polyfill/index.min.js
  - https://cdn.jsdelivr.net/npm/mathjax/es5/tex-mml-chtml.js
  # Table Sort
  - https://cdn.jsdelivr.net/npm/tablesort/dist/tablesort.min.js
  - javascripts/tablesort.js
  # mermaid
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js

extra_css:
  - stylesheets/fonts.css
  - stylesheets/theme.css
  # neoteroi
  - stylesheets/neoteroi-v1.1.2.css

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  # 该插件本地编辑时关闭，CI 时自动开启
  - git-committers:
      enabled: false
      repository: lan-kehan/lan-kehan.github.io
      branch: main
  - glightbox
  # - drawio
  - tags
  - search
  - include_dir_to_nav:
      recurse: false
